### ISSUE TITLE
Error when importing database dump: Cannot add foreign key constraint 

### ISSUE THREAD

**Issue by thomasaull** [Sebiworld/AppApi#3]
When exporting a MySql dump with the `ProcessDatabaseBackups` module and importing it again, I'm getting the error:
```
Error in query (1215): Cannot add foreign key constraint
```

Apparently the line:
```
CONSTRAINT `appapi_apikeys_ibfk_1` FOREIGN KEY (`application_id`) REFERENCES `appapi_applications` (`id`) ON DELETE CASCADE
```
is the problem here since the table `appapi_applications` does not exist yet.

I was able to fix this issue by moving the blocks `DROP TABLE IF EXISTS 'appapi_applications';` and `CREATE TABLE 'appapi_applications' …` and `INSERT INTO 'appapi_applications' …` to the top of the file.

**Comment by Sebiworld** [comment]
Yeah, I have already encountered these problems, too. The only problem is that the appapi_applications table must be created before appapi_apikeys. The foreign-keys are useful, because when an application is deleted, the apikeys will automatically deleted as well. But maybe it is better to implement this as php logic, since I cannot influence in which order the tables will be created from ProcessDatabaseBackups.

**Comment by Sebiworld** [comment]
My last commit should fix this issue. On new installations the created database-scheme will no longer contain foreign-key constraints. 

I tried to remove them on update automatically, but I think that could be complicated because we need to know the names of the constraints to delete them. My foreign-key constraint for the table appapi_apikeys was called appapi_apikeys_ibfk_1, but I think that could differ depending on the database-system used.

So, my plan is to add a message to the update-description, that the constraints can be deleted manually like this: ALTER TABLE appapi_apikeys DROP FOREIGN KEY appapi_apikeys_ibfk_1;
