### ISSUE TITLE
There is no way to set the http response code

### ISSUE THREAD

**Issue by twinklebob** [Sebiworld/AppApi#6]
If someone successfully creates a record I'd like to return a `201` but it seems I'm stuck with `200` or the exception handler.

**Comment by twinklebob** [comment]
I'm pretty new to ProcessWire so I'm not quite sure of the best way to solve this, but one approach might be to include it in the return data?

```php
// Example return data
return [
    'httpStatus' => 201,
    'otherKey' => 'otherValue'
];
```

And then in `Router.php`:

```php
$status = 200;

if(is_array($return) && $return['httpStatus']) {
    $status = $return['httpStatus'];
    unset($return['httpStatus']);
}

AppApi::sendResponse($status, $return);
```

If that sounds reasonable I'm happy to do a PR for it.

**Comment by twinklebob** [comment]
Alternatively there needs to be a function we can use to override the status.

**Comment by twinklebob** [comment]
On further thought around this, relying on the return data is a bit too hacky. So I've created a PR with a function in `AppApiHelper`. There might be a better place for this though?

**Comment by thomasaull** [comment]
Personally I think, it's not a bad idea to wrap the return in a custom function to be able to provide a status code. I think Laravel does this in a similar way if I'm not mistaken. We could keep the default return for backwards compatibility aswell.

Maybe it would be a good idea if we could use the `AppApi::sendResponse` directly? I provides all the params we would need. Maybe this would already be possible without changes since `AppApi::sendResponse` exits after sending the response to the client?

**Comment by twinklebob** [comment]
Hi @thomasaull I was trying to avoid that because I was worried about exception handling, but that should still work as expected. I can't see why that wouldn't work tbh. I'd overlooked the fact that sendResponse exits when it is complete, hence my thought that I needed something else.

I think it's fair to say that the PR can be thrown away and I'll close this ticket.
